version: '3'

services:
  web:
    build:
      context: ./
    restart: unless-stopped
    container_name: ${PROJECT_NAME}-${NODE_ENV:-development}
    expose:
      - "${BIND_PORT:-5000}"
    env_file:
      - ./.env

