version: "3"
services:
  app:
    image: backend
    build: .
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres
    ports:
      - 5432:5432
    restart: always
    environment:
      - POSTGRES_PASSWORD=password123
      - POSTGRES_USER=password123
      - POSTGRES_DB=password123
      - PGPORT=5433

